version: "3.1"

services:                   
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Pa55w0rd2021"
            MSSQL_PID: "Express"
        ports: 
            - "1433:1433"

    policlinic:
        image: barrierofdust/policlinicserver
        restart: on-failure
        container_name: "policlinic"
        environment: 
            DBServer: ms-sql-server
        ports: 
            - "8080:80" 
    
    client:
        depends_on: 
            - policlinic
        image: barrierofdust/policlinicclient
        ports: 
            - "3000:3000"
